// Registro schema-driven de entidades CRUD.
// Dados puros (serializáveis): podem ser importados pelo servidor e pelo cliente.
import type { CrudEntitySchema } from "./types";
import {
  BAIRRO,
  BLING_CATEGORIA,
  BLING_FORMATO,
  BLING_SITUACAO,
  BLING_SITUACAO_DEPOSITO,
  BLING_TIPO_PESSOA,
  BLING_TIPO_PRODUTO,
  BLING_VENDEDOR,
  CAMPOS_BANCARIOS,
  CAMPOS_CLIENTE_PEDIDO,
  CELULAR,
  CEP_BRASIL,
  CEST_TEXTIL,
  CFOP,
  CIDADE_SYSTEX,
  CLI_ID,
  CNPJ_2,
  CNPJ_4,
  CNPJ_9,
  CODIGO_BARRAS,
  CODIGO_PEDIDO,
  CODIGO_PRODUTO,
  COLEÇÃO,
  COLEÇÃO_INTERNACIONAL,
  COMPLEMENTO,
  COMPRADO_FABRICADO,
  CONTA_ESTOQUE,
  COR_ESTOQUE,
  DADOS_CONTATO,
  DATA_EMISSAO,
  DDD_TELEFONE,
  DDD_CELULAR,
  DEPOSITO_PADRAO,
  DESCONSIDERAR_SALDO,
  DESCONTO_SPD,
  DESCRICAO_CURTA,
  DISPONIVEL_INTERNET,
  EMAIL,
  EMAIL_NFE,
  EMPRESA_PEDIDO,
  ENCARGOS,
  ENDERECO_SYSTEX,
  FANTASIA,
  FORMA_PAGAMENTO,
  FRE_VIA,
  FUNCIONARIO_REPRESENTANTE,
  GRUPO_SUBGRUPO_ITEM,
  INSCRICAO_ESTADUAL,
  LARGURA,
  LINHA,
  METRAGEM,
  MOEDA,
  NATUREZA_OPERACAO,
  NCM_TEXTIL,
  NIVEL_PRODUTO,
  NOME_PRODUTO,
  NOME_RAZAO_SOCIAL,
  NUMERO,
  OBSERVACOES,
  ORIGEM_MERCADORIA,
  PEDIDO_MAE,
  PEDIDO_CLIENTE,
  PESO_OZ,
  PIX_SYSTEX,
  PORTADOR,
  PRECO,
  PRECO_CUSTO,
  PRODUTO_PROTOTIPO,
  QUANTIDADE_TOTAL,
  SALDO,
  SEQUENCIA_ENDERECO,
  SITUACAO_CLIENTE,
  SITUACAO_FORNECEDOR,
  SITUACAO_PRODUTO,
  SITUACAO_VENDA,
  STATUS_PEDIDO,
  TELEFONE,
  TIPO_CONTA,
  TIPO_CODIGO_EAN,
  TIPO_FORNECEDOR,
  TIPO_FRETE,
  TIPO_FRETE_PEDIDO,
  TIPO_PECA_PEDIDO,
  TIPO_PEDIDO,
  TIPO_PESSOA_SYSTEX,
  TIPO_PRODUTO,
  TIPO_PRODUTO_PEDIDO,
  TIPO_PROMOCAO,
  TIPO_SOCIO,
  UF_BRASIL,
  UNIDADE_MEDIDA,
  VALOR_BRUTO,
  VALOR_LIQUIDO,
} from "./help";

export const CRUD_ENTITIES: Record<string, CrudEntitySchema> = {
  "bling:produtos": {
    provider: "bling",
    entity: "produtos",
    title: "Produtos do Bling",
    description:
      "Produtos cadastrados no Bling V3. A edição usa o PUT de substituição da API (validações do Bling podem rejeitar a gravação; a mensagem completa é exibida). A exclusão é feita pelo módulo Produtos (2 passos: situação E + excluir).",
    idField: "id",
    basePath: "/produtos",
    searchParamName: "nome",
    disableDelete: true,
    fields: [
      { name: "codigo", label: "Código", type: "text", column: true, info: CODIGO_PRODUTO },
      { name: "nome", label: "Nome", type: "text", required: true, column: true, info: NOME_PRODUTO },
      {
        name: "tipo",
        label: "Tipo",
        type: "select",
        required: true,
        options: [
          { value: "P", label: "P · Produto" },
          { value: "S", label: "S · Serviço" },
        ],
        column: true,
        info: BLING_TIPO_PRODUTO,
      },
      {
        name: "formato",
        label: "Formato",
        type: "select",
        options: [
          { value: "S", label: "S · Simples" },
          { value: "V", label: "V · Variável" },
        ],
        info: BLING_FORMATO,
      },
      {
        name: "situacao",
        label: "Situação",
        type: "select",
        options: [
          { value: "A", label: "A · Ativo" },
          { value: "I", label: "I · Inativo" },
          { value: "E", label: "E · Excluído" },
        ],
        column: true,
        info: BLING_SITUACAO,
      },
      { name: "preco", label: "Preço", type: "number", column: true, info: PRECO },
      { name: "precoCusto", label: "Preço de custo", type: "number", info: PRECO_CUSTO },
      { name: "descricaoCurta", label: "Descrição curta", type: "text", info: DESCRICAO_CURTA },
    ],
  },
  "bling:categorias-produto": {
    provider: "bling",
    entity: "categorias-produto",
    title: "Categorias de Produto (Bling)",
    description:
      "Categorias de produto do Bling V3. Use o ID da categoria para vincular produtos (ex.: em perfis de produto).",
    idField: "id",
    basePath: "/categorias/produtos",
    searchParamName: "none",
    fields: [
      {
        name: "id",
        label: "ID da categoria",
        type: "number",
        required: true,
        column: true,
        help: "Usado para vincular a categoria a um produto.",
        info: BLING_CATEGORIA,
      },
      {
        name: "descricao",
        label: "Descrição",
        type: "text",
        required: true,
        column: true,
        info: {
          oQue: "Nome da categoria de produto.",
          regras: ["Não duplicar categorias com o mesmo nome.", "Padrão: MAIÚSCULO, sem acento quando o sistema não aceitar."],
          exemplos: ["CAMISETAS", "TECIDOS", "CAMA MESA", "JEANS"],
        },
      },
    ],
  },
  "bling:depositos": {
    provider: "bling",
    entity: "depositos",
    title: "Depósitos (Bling)",
    description:
      "Depósitos de estoque do Bling V3. O Bling não possui endpoint de exclusão de depósito; para desativar, altere a situação para Inativo.",
    idField: "id",
    basePath: "/depositos",
    searchParamName: "descricao",
    disableDelete: true,
    fields: [
      {
        name: "descricao",
        label: "Descrição",
        type: "text",
        required: true,
        column: true,
        info: {
          oQue: "Nome do depósito de estoque (onde a mercadoria física é armazenada).",
          regras: ["Evitar nomes duplicados.", "Padrão usual: Geral, Expedição, Filial, Estoque 2."],
          exemplos: ["Geral", "Expedição", "Filial Campinas"],
        },
      },
      {
        name: "situacao",
        label: "Situação",
        type: "select",
        asNumber: true,
        required: true,
        options: [
          { value: "1", label: "1 · Ativo" },
          { value: "0", label: "0 · Inativo" },
        ],
        column: true,
        info: BLING_SITUACAO_DEPOSITO,
      },
      {
        name: "padrao",
        label: "Depósito padrão?",
        type: "boolean",
        required: true,
        column: true,
        info: DEPOSITO_PADRAO,
      },
      {
        name: "desconsiderarSaldo",
        label: "Desconsiderar saldo?",
        type: "boolean",
        required: true,
        column: true,
        info: DESCONSIDERAR_SALDO,
      },
    ],
  },
  "bling:vendedores": {
    provider: "bling",
    entity: "vendedores",
    title: "Vendedores (Bling)",
    description:
      "Vendedores do Bling V3. O Bling não expõe endpoints de criação/edição/exclusão de vendedor — somente consulta.",
    idField: "id",
    basePath: "/vendedores",
    searchParamName: "nomeContato",
    readOnly: true,
    fields: [
      { name: "id", label: "ID", type: "number", column: true, info: { oQue: "Identificador numérico do vendedor no Bling.", regras: ["Gerado pelo Bling — não informar ao criar."] } },
      { name: "contato.nome", label: "Nome", type: "text", column: true, info: { oQue: "Nome do contato vinculado ao vendedor (pessoa que vende).", regras: ["Vem do cadastro de contatos do Bling."] } },
      { name: "contato.situacao", label: "Situação", type: "text", column: true, info: BLING_SITUACAO },
      { name: "descontoLimite", label: "Desconto limite", type: "number", column: true, info: BLING_VENDEDOR },
    ],
  },
  "bling:transportadoras": {
    provider: "bling",
    entity: "transportadoras",
    title: "Transportadoras (Bling)",
    description:
      "Transportadoras cadastradas como contato do Bling V3 (o Bling não tem endpoint próprio de transportadora; a listagem filtra contatos do tipo Transportadora). Somente consulta.",
    idField: "id",
    basePath: "/contatos",
    searchParamName: "pesquisa",
    tipoContato: "Transportador",
    readOnly: true,
    fields: [
      { name: "id", label: "ID", type: "number", column: true, info: { oQue: "Identificador do contato no Bling.", regras: ["Gerado pelo Bling."] } },
      { name: "nome", label: "Nome", type: "text", column: true, info: { oQue: "Nome/razão social da transportadora.", regras: ["Use a razão social oficial (consta do CNPJ)."], exemplos: ["TRANSPORTADORA BRASIL LTDA"] } },
      {
        name: "numeroDocumento",
        label: "CPF / CNPJ",
        type: "text",
        column: true,
        info: {
          oQue: "Documento da transportadora (CNPJ ou CPF).",
          regras: ["Somente dígitos, sem máscara.", "CNPJ precisa ser válido (dígitos verificadores)."],
          exemplos: ["12.345.678/0001-95 → 12345678000195"],
        },
      },
      {
        name: "situacao",
        label: "Situação",
        type: "select",
        options: [
          { value: "A", label: "A · Ativo" },
          { value: "I", label: "I · Inativo" },
          { value: "E", label: "E · Excluído" },
          { value: "S", label: "S · Sem movimento" },
        ],
        column: true,
        info: BLING_SITUACAO,
      },
      { name: "telefone", label: "Telefone", type: "text", info: TELEFONE },
      { name: "email", label: "E-mail", type: "text", info: EMAIL },
    ],
  },
  "bling:pedidos-venda": {
    provider: "bling",
    entity: "pedidos-venda",
    title: "Pedidos de Venda (Bling)",
    description:
      "Pedidos de venda do Bling V3. Somente consulta: criação/edição/exclusão de pedidos não são expostos pelo CRUD genérico para evitar alterações destrutivas em faturamento.",
    idField: "id",
    basePath: "/pedidos/vendas",
    searchParamName: "none",
    readOnly: true,
    fields: [
      { name: "id", label: "ID", type: "number", column: true, info: { oQue: "Identificador do pedido no Bling.", regras: ["Gerado pelo Bling."] } },
      { name: "numero", label: "Número", type: "number", column: true, info: { oQue: "Número do pedido de venda (sequencial).", regras: ["Referência comercial do pedido (nos documentos e na troca com o cliente)."], exemplos: ["10025"] } },
      { name: "data", label: "Data", type: "date", column: true, info: DATA_EMISSAO },
      { name: "contato.nome", label: "Cliente", type: "text", column: true, info: { oQue: "Nome do cliente (contato) do pedido.", regras: ["Consulta apenas — o cadastro completo está na tela Clientes."] } },
      { name: "situacao.nome", label: "Situação", type: "text", column: true, info: { oQue: "Situação atual do pedido (aberto, aprovado, faturado, cancelado...).", regras: ["Gerida pelo fluxo de vendas do Bling."] } },
      { name: "loja.nome", label: "Loja", type: "text", column: true, info: { oQue: "Loja/estabelecimento emissor do pedido no Bling.", regras: ["Define série e cadastro fiscal usados no faturamento."] } },
      { name: "total", label: "Total", type: "number", column: true, info: VALOR_LIQUIDO },
      { name: "totalProdutos", label: "Total produtos", type: "number", info: VALOR_BRUTO },
    ],
  },
  "bling:contatos": {
    provider: "bling",
    entity: "contatos",
    title: "Contatos no Bling",
    description:
      "Clientes, fornecedores e transportadoras cadastrados no Bling V3.",
    idField: "id",
    basePath: "/contatos",
    fields: [
      {
        name: "tipo",
        label: "Tipo de pessoa",
        type: "select",
        required: true,
        options: [
          { value: "F", label: "F · Física" },
          { value: "J", label: "J · Jurídica" },
          { value: "E", label: "E · Estrangeira" },
        ],
        column: true,
        info: BLING_TIPO_PESSOA,
      },
      { name: "nome", label: "Nome", type: "text", required: true, column: true, info: NOME_RAZAO_SOCIAL },
      {
        name: "numeroDocumento",
        label: "CPF / CNPJ",
        type: "text",
        column: true,
        info: {
          oQue: "Documento do contato (CPF ou CNPJ).",
          regras: ["Somente dígitos, sem máscara.", "A validação dos dígitos verificadores ocorre no Bling."],
          exemplos: ["12345678000195 (CNPJ)", "12345678909 (CPF)"],
        },
      },
      {
        name: "situacao",
        label: "Situação",
        type: "select",
        options: [
          { value: "A", label: "A · Ativo" },
          { value: "I", label: "I · Inativo" },
          { value: "E", label: "E · Excluído" },
          { value: "S", label: "S · Sem movimento" },
        ],
        column: true,
        info: BLING_SITUACAO,
      },
      { name: "codigo", label: "Código", type: "text", info: { oQue: "Código de referência do contato (interno do cliente/vendedor).", regras: ["Único — usado para casar com sistemas legados."], exemplos: ["C101"] } },
      { name: "fantasia", label: "Nome fantasia", type: "text", info: FANTASIA },
      { name: "telefone", label: "Telefone", type: "text", info: TELEFONE },
      { name: "celular", label: "Celular", type: "text", info: CELULAR },
      { name: "email", label: "E-mail", type: "text", info: EMAIL },
    ],
  },
  "systextil:cliente": {
    provider: "systextil",
    entity: "cliente",
    title: "Clientes (Systêxtil)",
    description:
      "Clientes cadastrados no ERP Systêxtil, com endereço, contato e condições comerciais.",
    idField: "cnpj_9",
    keyFields: ["cnpj_9", "cnpj_4", "cnpj_2"],
    basePath: "/pessoa/v1/cliente",
    fields: [
      { name: "cnpj_9", label: "CNPJ/CPF (9 dígitos)", type: "number", required: true, column: true, info: CNPJ_9 },
      { name: "cnpj_4", label: "CNPJ (4 dígitos)", type: "number", required: true, column: true, info: CNPJ_4 },
      { name: "cnpj_2", label: "CNPJ (2 dígitos)", type: "number", required: true, column: true, info: CNPJ_2 },
      { name: "nome_cliente", label: "Nome / Razão social", type: "text", required: true, column: true, info: NOME_RAZAO_SOCIAL },
      { name: "fantasia_cliente", label: "Nome fantasia", type: "text", info: FANTASIA },
      {
        name: "fisica_juridica",
        label: "Física / Jurídica",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Pessoa Física" },
          { value: "2", label: "2 · Pessoa Jurídica" },
        ],
        column: true,
        info: TIPO_PESSOA_SYSTEX,
      },
      { name: "cep", label: "CEP", type: "number", info: CEP_BRASIL },
      { name: "logradouro", label: "Logradouro", type: "text", info: ENDERECO_SYSTEX("logradouro") },
      { name: "numero", label: "Número", type: "text", info: NUMERO },
      { name: "complemento", label: "Complemento", type: "text", info: COMPLEMENTO },
      { name: "bairro", label: "Bairro", type: "text", info: BAIRRO },
      { name: "cidade_descricao", label: "Cidade", type: "text", column: true, info: CIDADE_SYSTEX },
      { name: "estado", label: "UF", type: "text", column: true, info: UF_BRASIL },
      { name: "ddd_telefone", label: "DDD telefone", type: "number", info: DDD_TELEFONE },
      { name: "telefone", label: "Telefone", type: "number", info: TELEFONE },
      { name: "ddd_celular", label: "DDD celular", type: "text", info: DDD_CELULAR },
      { name: "celular", label: "Celular", type: "number", info: CELULAR },
      { name: "email", label: "E-mail", type: "text", column: true, info: EMAIL },
      { name: "email_nfe", label: "E-mail NF-e", type: "text", info: EMAIL_NFE },
      { name: "inscricao_estadual", label: "Inscrição estadual", type: "text", info: INSCRICAO_ESTADUAL },
      {
        name: "situacao_cliente",
        label: "Situação",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Ativo" },
          { value: "2", label: "2 · Inativo" },
        ],
        column: true,
        info: SITUACAO_CLIENTE,
      },
      { name: "tipo_frete", label: "Tipo frete", type: "number", placeholder: "0-5", info: TIPO_FRETE },
      { name: "forma_pagamento", label: "Forma de pagamento (código)", type: "text", info: FORMA_PAGAMENTO },
      { name: "codigo_banco", label: "Código do banco", type: "number", info: CAMPOS_BANCARIOS },
      { name: "agencia_banco", label: "Agência", type: "number", info: CAMPOS_BANCARIOS },
      { name: "nome_contato", label: "Nome do contato", type: "text", info: DADOS_CONTATO },
      { name: "seq_endereco", label: "Seq. endereço", type: "number", info: SEQUENCIA_ENDERECO },
      { name: "data_fundacao", label: "Data de fundação", type: "date", info: { oQue: "Data de abertura/fundação da empresa do cliente.", regras: ["Se conhecida (consta do CNPJ).", "Opcional para pessoa física."], exemplos: ["1995-03-12"] } },
    ],
  },
  "systextil:fornecedor": {
    provider: "systextil",
    entity: "fornecedor",
    title: "Fornecedores (Systêxtil)",
    description:
      "Fornecedores cadastrados no ERP Systêxtil, com dados de contato, bancários, impostos e materiais fornecidos.",
    idField: "cnpj_9_fornecedor",
    keyFields: ["cnpj_9_fornecedor", "cnpj_4_fornecedor", "cnpj_2_fornecedor"],
    basePath: "/pessoa/v1/fornecedor",
    fields: [
      { name: "cnpj_9_fornecedor", label: "CNPJ/CPF (9 dígitos)", type: "number", required: true, column: true, info: CNPJ_9 },
      { name: "cnpj_4_fornecedor", label: "CNPJ (4 dígitos)", type: "number", required: true, column: true, info: CNPJ_4 },
      { name: "cnpj_2_fornecedor", label: "CNPJ (2 dígitos)", type: "number", required: true, column: true, info: CNPJ_2 },
      { name: "nome_fornecedor", label: "Nome / Razão social", type: "text", column: true, info: NOME_RAZAO_SOCIAL },
      { name: "nome_fantasia", label: "Nome fantasia", type: "text", info: FANTASIA },
      { name: "tipo_fornecedor_id", label: "Código do tipo", type: "number", required: true, placeholder: "código do tipo", info: TIPO_FORNECEDOR },
      { name: "codigo_fornecedor", label: "Código do fornecedor", type: "text", info: { oQue: "Código interno do fornecedor no ERP.", regras: ["Usado pela integração para casar itens comprados com o fornecedor.", "Sem espaços nem caracteres especiais."], exemplos: ["FOR00121"] } },
      { name: "cep_fornecedor", label: "CEP", type: "number", required: true, info: CEP_BRASIL },
      { name: "endereco_fornecedor", label: "Endereço", type: "text", required: true, column: true, info: ENDERECO_SYSTEX("endereco_fornecedor") },
      { name: "numero_fornecedor", label: "Número", type: "text", required: true, info: NUMERO },
      { name: "complemento_fornecedor", label: "Complemento", type: "text", info: COMPLEMENTO },
      { name: "bairro_fornecedor", label: "Bairro", type: "text", required: true, info: BAIRRO },
      { name: "cidade_fornecedor_id", label: "Código da cidade", type: "number", required: true, info: CIDADE_SYSTEX },
      { name: "cidade_fornecedor_descricao", label: "Cidade", type: "text", column: true, info: CIDADE_SYSTEX },
      { name: "codigo_ibge_fornecedor", label: "Código IBGE", type: "number", info: { oQue: "Código IBGE do município (7 dígitos).", regras: ["Precisa bater com a cidade informada (validação da NF-e de entrada).", "Opcional, usado para conferir o cadastro municipal."], exemplos: ["3550308 (São Paulo)", "4202404 (Blumenau)"] } },
      { name: "estado_fornecedor", label: "UF", type: "text", column: true, info: UF_BRASIL },
      { name: "telefone_fornecedor", label: "Telefone", type: "number", column: true, info: TELEFONE },
      { name: "ddd_celular_fornecedor", label: "DDD celular", type: "number", info: DDD_CELULAR },
      { name: "celular_fornecedor", label: "Celular", type: "number", info: CELULAR },
      { name: "site_fornecedor", label: "Site", type: "text", info: { oQue: "Endereço do site institucional do fornecedor.", regras: ["Apenas o domínio (ex.: www.tecidossubra.com.br)."] } },
      { name: "email_fornecedor", label: "E-mail", type: "text", column: true, info: EMAIL },
      { name: "email_nfe_fornecedor", label: "E-mail NF-e", type: "text", info: EMAIL_NFE },
      { name: "inscricao_estadual_fornecedor", label: "Inscrição estadual", type: "text", info: INSCRICAO_ESTADUAL },
      { name: "inscricao_municipal_fornecedor", label: "Inscrição municipal", type: "text", info: { oQue: "Inscrição municipal (IM) — usada para fornecedores de serviço (ISSQN).", regras: ["Obrigatória para prestadores de serviço (tinturaria, beneficiamento, transporte).", "Na NF de serviço (NFS-e) a IM substitui a IE."], exemplos: ["7208451 (IM de prestador de serviço)"] } },
      { name: "observacoes_fornecedor", label: "Observações", type: "text", info: OBSERVACOES },
      {
        name: "situacao_fornecedor",
        label: "Situação",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Ativo" },
          { value: "2", label: "2 · Inativo" },
          { value: "3", label: "3 · Não qualificado" },
          { value: "9", label: "9 · Pré-cadastro" },
        ],
        column: true,
        info: SITUACAO_FORNECEDOR,
      },
      { name: "condicao_pagamento_fornecedor_id", label: "Condição de pagamento (código)", type: "number", info: FORMA_PAGAMENTO },
      { name: "nome_contato_fornecedor", label: "Nome do contato", type: "text", required: true, info: DADOS_CONTATO },
      { name: "banco_fornecedor_id", label: "Código do banco", type: "number", required: true, info: CAMPOS_BANCARIOS },
      { name: "agencia_fornecedor", label: "Agência", type: "number", info: CAMPOS_BANCARIOS },
      { name: "conta_fornecedor", label: "Conta", type: "number", info: CAMPOS_BANCARIOS },
      {
        name: "tipo_conta",
        label: "Tipo de conta",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Normal" },
          { value: "2", label: "2 · Poupança" },
        ],
        info: TIPO_CONTA,
      },
      { name: "moeda_id", label: "Código da moeda", type: "number", placeholder: "código da moeda", info: MOEDA },
      {
        name: "tipo_chave_pix",
        label: "Tipo de chave PIX",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · CPF ou CNPJ" },
          { value: "2", label: "2 · E-mail" },
          { value: "3", label: "3 · Celular" },
          { value: "4", label: "4 · Chave aleatória" },
        ],
        info: PIX_SYSTEX,
      },
      { name: "chave_pix", label: "Chave PIX", type: "text", info: PIX_SYSTEX },
      {
        name: "tipo_socio",
        label: "Sócio?",
        type: "select",
        options: [
          { value: "false", label: "Não sócio" },
          { value: "true", label: "Sócio" },
        ],
        info: TIPO_SOCIO,
      },
    ],
  },
  "systextil:produto": {
    provider: "systextil",
    entity: "produto",
    title: "Produtos (Systêxtil)",
    description:
      "Produtos e materiais cadastrados no ERP Systêxtil, organizados por nível, grupo, subgrupo e item de estrutura.",
    idField: "item_estrutura_id",
    keyFields: ["nivel_produto", "grupo_id", "subgrupo_id", "item_estrutura_id"],
    searchField: "descricao_produto",
    basePath: "/material/v1/produto",
    fields: [
      {
        name: "nivel_produto",
        label: "Nível",
        type: "select",
        required: true,
        options: [
          { value: "1", label: "1 · Peça" },
          { value: "2", label: "2 · Tecido" },
          { value: "4", label: "4 · Tecido Cru" },
          { value: "5", label: "5 · Serviços" },
          { value: "7", label: "7 · Fio" },
          { value: "8", label: "8 · Largura Tecido" },
          { value: "9", label: "9 · Material Comprado" },
        ],
        column: true,
        info: NIVEL_PRODUTO,
      },
      { name: "grupo_id", label: "Grupo", type: "text", required: true, column: true, info: GRUPO_SUBGRUPO_ITEM },
      { name: "subgrupo_id", label: "Subgrupo", type: "text", required: true, column: true, info: GRUPO_SUBGRUPO_ITEM },
      { name: "item_estrutura_id", label: "Item de estrutura", type: "text", required: true, column: true, info: GRUPO_SUBGRUPO_ITEM },
      { name: "item_estrutura_descricao", label: "Item (descrição)", type: "text", info: { oQue: "Descrição auto-gerada pela estrutura do ERP (nível + grupo + subgrupo + item).", regras: ["Geralmente mantida pelo ERP — editar apenas com segurança."] } },
      { name: "descricao_produto", label: "Descrição", type: "text", column: true, info: {
        oQue: "Descrição comercial do material (tecido, peça, fio, serviço).",
        regras: ["Usada em etiquetas, pedidos e notas.", "Incluir referência da estrutura quando útil."],
        exemplos: ["TECIDO LENCOL ELEGANCE ALGODAO TRICOLINE", "CAMISETA MALHA PENTEADA GOLA V"],
      } },
      { name: "descricao_produto_complementar", label: "Descrição complementar", type: "text", info: DESCRICAO_CURTA },
      {
        name: "situacao_produto",
        label: "Situação",
        type: "select",
        asNumber: true,
        options: [
          { value: "0", label: "0 · Ativo" },
          { value: "1", label: "1 · Inativo" },
          { value: "2", label: "2 · Lançamento" },
        ],
        column: true,
        info: SITUACAO_PRODUTO,
      },
      { name: "classificacao_fiscal", label: "Classificação fiscal", type: "text", info: NCM_TEXTIL },
      { name: "cest", label: "CEST", type: "text", info: CEST_TEXTIL },
      { name: "codigo_barras", label: "Código de barras", type: "text", info: CODIGO_BARRAS },
      { name: "unidade_medida_id", label: "Unidade de medida (código)", type: "text", info: UNIDADE_MEDIDA },
      { name: "unidade_medida_descricao", label: "Unidade de medida", type: "text", column: true, info: UNIDADE_MEDIDA },
      { name: "linha_produto_id", label: "Linha (código)", type: "number", info: LINHA },
      { name: "linha_produto_descricao", label: "Linha", type: "text", column: true, info: LINHA },
      { name: "colecao_id", label: "Coleção (código)", type: "number", info: COLEÇÃO },
      { name: "colecao_descricao", label: "Coleção", type: "text", column: true, info: COLEÇÃO },
      { name: "artigo_id", label: "Artigo (código)", type: "number", info: { oQue: "Código do artigo/desenho do material (ex.: 100/4 do sistema antigo).", regras: ["Identifica o desenho de tecelagem ou o modelo de peça.", "Combine com o nível para não duplicar artigos."], exemplos: ["100/4", "200/1"] } },
      { name: "artigo_descricao", label: "Artigo", type: "text", info: { oQue: "Descrição do artigo/desenho.", regras: ["Curta — acompanha o código do artigo."] } },
      { name: "grade_tamanho_id", label: "Grade (código)", type: "number", info: CLI_ID },
      { name: "conta_estoque_id", label: "Conta de estoque (código)", type: "number", info: CONTA_ESTOQUE },
      {
        name: "comprado_fabricado",
        label: "Comprado / Fabricado",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Comprado" },
          { value: "2", label: "2 · Fabricado" },
        ],
        info: COMPRADO_FABRICADO,
      },
      { name: "tipo_produto", label: "Tipo de produto", type: "number", placeholder: "conforme nível", info: TIPO_PRODUTO },
      {
        name: "origem_produto",
        label: "Origem",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Nacional" },
          { value: "2", label: "2 · Importado" },
          { value: "3", label: "3 · Sem classificação" },
        ],
        info: ORIGEM_MERCADORIA,
      },
      {
        name: "tipo_codigo_ean",
        label: "Grade de EAN",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Por cor" },
          { value: "2", label: "2 · Por tamanho" },
        ],
        info: TIPO_CODIGO_EAN,
      },
      { name: "cor_de_estoque", label: "Cor/sortimento estoque", type: "text", info: COR_ESTOQUE },
      { name: "largura", label: "Largura", type: "number", info: LARGURA },
      { name: "metragem", label: "Metragem do rolo", type: "number", info: METRAGEM },
      { name: "peso_oz", label: "Peso (oz)", type: "number", info: PESO_OZ },
      { name: "codigo_acompanhamento", label: "Código de acompanhamento", type: "number", info: { oQue: "Código de acompanhamento de produção do item.", regras: ["Usado no PCP para rastrear o item por lote/OP.", "Geralmente gerado pelo ERP — editar apenas com segurança."] } },
      { name: "observacao_produto", label: "Observações", type: "text", info: OBSERVACOES },
      {
        name: "produto_prototipo",
        label: "Produto protótipo?",
        type: "select",
        options: [
          { value: "true", label: "true" },
          { value: "false", label: "false" },
        ],
        info: PRODUTO_PROTOTIPO,
      },
    ],
  },
  "systextil:colecao": {
    provider: "systextil",
    entity: "colecao",
    title: "Coleções (Systêxtil)",
    description:
      "Coleções de produtos cadastradas no ERP Systêxtil. Endpoint /material/v1/colecao retornou 404 no tenant PRD (2026-09-05) - recurso pode estar desabilitado na assinatura. Verifique com a Systêxtil antes de usar.",
    idField: "colecao_id",
    keyFields: ["colecao_id"],
    searchField: "colecao_descricao",
    basePath: "/material/v1/colecao",
    fields: [
      { name: "colecao_id", label: "Código da coleção", type: "number", required: true, column: true, info: { oQue: "Código numérico da coleção no ERP.", regras: ["Sequencial/único — gera o vínculo dos produtos."], exemplos: ["1", "25"] } },
      { name: "colecao_descricao", label: "Descrição", type: "text", required: true, column: true, info: COLEÇÃO },
      { name: "colecao_descricao_ingles", label: "Descrição (inglês)", type: "text", info: COLEÇÃO_INTERNACIONAL },
      { name: "colecao_descricao_espanhol", label: "Descrição (espanhol)", type: "text", info: COLEÇÃO_INTERNACIONAL },
      {
        name: "disponivel_internet",
        label: "Disponível na internet?",
        type: "select",
        options: [
          { value: "true", label: "true" },
          { value: "false", label: "false" },
        ],
        info: DISPONIVEL_INTERNET,
      },
    ],
  },
  "systextil:pedido-venda": {
    provider: "systextil",
    entity: "pedido-venda",
    title: "Pedidos de Venda (Systêxtil)",
    description:
      "Pedidos de venda do ERP Systêxtil, com cliente, itens, condições comerciais, transporte e faturamento.",
    idField: "codigo_pedido",
    keyFields: ["codigo_empresa_pedido", "codigo_pedido"],
    searchField: "nome_cliente",
    basePath: "/venda/v1/pedido/venda",
    fields: [
      { name: "codigo_empresa_pedido", label: "Empresa", type: "number", required: true, column: true, info: EMPRESA_PEDIDO },
      { name: "codigo_pedido", label: "Código do pedido", type: "number", required: true, column: true, info: CODIGO_PEDIDO },
      { name: "codigo_pedido_cliente", label: "Pedido do cliente", type: "text", column: true, info: PEDIDO_CLIENTE },
      { name: "cnpj9_cliente", label: "CNPJ/CPF do cliente (9)", type: "number", column: true, info: CAMPOS_CLIENTE_PEDIDO },
      { name: "cnpj4_cliente", label: "CNPJ do cliente (4)", type: "number", info: CNPJ_4 },
      { name: "cnpj2_cliente", label: "CNPJ do cliente (2)", type: "number", info: CNPJ_2 },
      { name: "nome_cliente", label: "Cliente", type: "text", column: true, info: { oQue: "Nome/razão social do cliente reproduzido no pedido.", regras: ["Deve ser igual ao cadastro do cliente (não usar apelido)."] } },
      { name: "estado_cliente", label: "UF do cliente", type: "text", info: UF_BRASIL },
      {
        name: "tipo_peca_pedido",
        label: "Tipo de peça",
        type: "select",
        options: [
          { value: "1", label: "1 · Peças" },
          { value: "2", label: "2 · Tecidos" },
          { value: "4", label: "4 · Tecidos crus" },
          { value: "7", label: "7 · Fios" },
        ],
        info: TIPO_PECA_PEDIDO,
      },
      {
        name: "tipo_pedido",
        label: "Tipo do pedido",
        type: "select",
        asNumber: true,
        options: [
          { value: "0", label: "0 · Programado" },
          { value: "1", label: "1 · Pronta entrega" },
        ],
        info: TIPO_PEDIDO,
      },
      {
        name: "tipo_produto_pedido",
        label: "Qualidade do produto",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Primeira qualidade" },
          { value: "2", label: "2 · Segunda qualidade" },
          { value: "3", label: "3 · Retalho" },
          { value: "4", label: "4 · Amostragem" },
          { value: "5", label: "5 · Exportação" },
          { value: "6", label: "6 · Desenvolvimento" },
        ],
        info: TIPO_PRODUTO_PEDIDO,
      },
      {
        name: "tipo_promocao_pedido",
        label: "Promoção",
        type: "select",
        asNumber: true,
        options: [
          { value: "0", label: "0 · Não é promoção" },
          { value: "1", label: "1 · É promoção" },
          { value: "2", label: "2 · É desconto" },
        ],
        info: TIPO_PROMOCAO,
      },
      { name: "origem_pedido", label: "Origem do pedido", type: "number", info: { oQue: "Código da origem do pedido (canal de venda).", regras: ["Ex.: balcão, telefone, web, representante — confira a tabela do ERP."], exemplos: ["1 (balcão)", "3 (representante)"] } },
      { name: "data_emissao", label: "Data de emissão", type: "date", column: true, info: DATA_EMISSAO },
      { name: "data_base_faturamento", label: "Data base faturamento", type: "date", info: { oQue: "Data base para cálculo de encargos/multa de atraso no faturamento.", regras: ["Normalmente = data de emissão ou data combinada de entrega."], exemplos: ["2026-09-05"] } },
      { name: "codigo_funcionario", label: "Funcionário (código)", type: "number", info: FUNCIONARIO_REPRESENTANTE },
      { name: "codigo_representante", label: "Representante (código)", type: "number", info: FUNCIONARIO_REPRESENTANTE },
      { name: "condicao_pagamento", label: "Condição de pagamento (código)", type: "number", column: true, info: FORMA_PAGAMENTO },
      { name: "percentual_desconto1", label: "Desconto 1 (%)", type: "number", info: DESCONTO_SPD },
      { name: "percentual_desconto2", label: "Desconto 2 (%)", type: "number", info: DESCONTO_SPD },
      { name: "percentual_desconto3", label: "Desconto 3 (%)", type: "number", info: DESCONTO_SPD },
      { name: "percentual_encargos", label: "Encargos (%)", type: "number", info: ENCARGOS },
      { name: "moeda_id", label: "Moeda (código)", type: "number", info: MOEDA },
      {
        name: "tipo_frete",
        label: "Tipo de frete",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Frete pago" },
          { value: "2", label: "2 · Frete a pagar" },
          { value: "3", label: "3 · Por conta de terceiros" },
          { value: "4", label: "4 · Cortesia" },
          { value: "5", label: "5 · Valor fechado" },
          { value: "6", label: "6 · Transporte próprio remetente" },
          { value: "7", label: "7 · Transporte próprio destinatário" },
        ],
        info: TIPO_FRETE_PEDIDO,
      },
      {
        name: "via_transporte",
        label: "Via",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Terrestre" },
          { value: "2", label: "2 · Aéreo" },
          { value: "3", label: "3 · Marítimo" },
          { value: "4", label: "4 · Ferroviário" },
          { value: "5", label: "5 · Fluvial" },
        ],
        info: FRE_VIA,
      },
      { name: "forma_pagamento_id", label: "Forma de pagamento (código)", type: "number", info: FORMA_PAGAMENTO },
      { name: "natureza_operacao", label: "Natureza da operação (código)", type: "number", info: NATUREZA_OPERACAO },
      { name: "cfop_principal", label: "CFOP principal", type: "text", info: CFOP },
      { name: "codigo_banco", label: "Código do portador", type: "number", info: PORTADOR },
      {
        name: "status_pedido",
        label: "Status",
        type: "select",
        asNumber: true,
        options: [
          { value: "0", label: "0 · Digitado" },
          { value: "1", label: "1 · Financeiro" },
          { value: "2", label: "2 · Liberado financeiro" },
          { value: "3", label: "3 · Faturamento" },
          { value: "4", label: "4 · A cancelar" },
          { value: "5", label: "5 · Cancelado" },
          { value: "9", label: "9 · Aberto na web" },
        ],
        column: true,
        info: STATUS_PEDIDO,
      },
      { name: "situacao_venda", label: "Situação da venda", type: "number", placeholder: "0/5/9/10/15/50/51/52/54/56/62/64/66/70/87", info: SITUACAO_VENDA },
      { name: "quantidade_total_pedido", label: "Quantidade total", type: "number", column: true, info: QUANTIDADE_TOTAL },
      { name: "valor_total_bruto_pedido", label: "Valor total bruto", type: "number", column: true, info: VALOR_BRUTO },
      { name: "valor_total_liquido_pedido", label: "Valor total líquido", type: "number", column: true, info: VALOR_LIQUIDO },
      { name: "quantidade_saldo_pedido", label: "Qtde. de saldo", type: "number", info: SALDO },
      { name: "valor_saldo_pedido", label: "Valor de saldo", type: "number", info: SALDO },
      { name: "pedido_mae", label: "Pedido mãe?", type: "select", options: [{ value: "S", label: "S" }, { value: "N", label: "N" }], info: PEDIDO_MAE },
    ],
  },
};

export function getCrudEntity(
  provider: string,
  entity: string
): CrudEntitySchema | null {
  return CRUD_ENTITIES[`${provider}:${entity}`] ?? null;
}