// Registro schema-driven de entidades CRUD.
// Dados puros (serializáveis): podem ser importados pelo servidor e pelo cliente.
import type { CrudEntitySchema } from "./types";

export const CRUD_ENTITIES: Record<string, CrudEntitySchema> = {
  "bling:contatos": {
    provider: "bling",
    entity: "contatos",
    title: "Contatos no Bling",
    description:
      "Clientes, fornecedores e transportadoras cadastrados no Bling V3.",
    idField: "id",
    basePath: "/contatos",
    fields: [
      {
        name: "tipo",
        label: "Tipo de pessoa",
        type: "select",
        required: true,
        options: [
          { value: "F", label: "F · Física" },
          { value: "J", label: "J · Jurídica" },
          { value: "E", label: "E · Estrangeira" },
        ],
        column: true,
      },
      { name: "nome", label: "Nome", type: "text", required: true, column: true },
      { name: "numeroDocumento", label: "CPF / CNPJ", type: "text", column: true },
      {
        name: "situacao",
        label: "Situação",
        type: "select",
        options: [
          { value: "A", label: "A · Ativo" },
          { value: "I", label: "I · Inativo" },
          { value: "E", label: "E · Excluído" },
          { value: "S", label: "S · Sem movimento" },
        ],
        column: true,
      },
      { name: "codigo", label: "Código", type: "text" },
      { name: "fantasia", label: "Nome fantasia", type: "text" },
      { name: "telefone", label: "Telefone", type: "text" },
      { name: "celular", label: "Celular", type: "text" },
      { name: "email", label: "E-mail", type: "text" },
    ],
  },
  "systextil:cliente": {
    provider: "systextil",
    entity: "cliente",
    title: "Clientes (Systêxtil)",
    description:
      "Clientes cadastrados no ERP Systêxtil, com endereço, contato e condições comerciais.",
    idField: "cnpj_9",
    keyFields: ["cnpj_9", "cnpj_4", "cnpj_2"],
    basePath: "/pessoa/v1/cliente",
    fields: [
      { name: "cnpj_9", label: "CNPJ/CPF (9 dígitos)", type: "number", required: true, column: true },
      { name: "cnpj_4", label: "CNPJ (4 dígitos)", type: "number", required: true, column: true },
      { name: "cnpj_2", label: "CNPJ (2 dígitos)", type: "number", required: true, column: true },
      { name: "nome_cliente", label: "Nome / Razão social", type: "text", required: true, column: true },
      { name: "fantasia_cliente", label: "Nome fantasia", type: "text" },
      {
        name: "fisica_juridica",
        label: "Física / Jurídica",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Pessoa Física" },
          { value: "2", label: "2 · Pessoa Jurídica" },
        ],
        column: true,
      },
      { name: "cep", label: "CEP", type: "number" },
      { name: "logradouro", label: "Logradouro", type: "text" },
      { name: "numero", label: "Número", type: "text" },
      { name: "complemento", label: "Complemento", type: "text" },
      { name: "bairro", label: "Bairro", type: "text" },
      { name: "cidade_descricao", label: "Cidade", type: "text", column: true },
      { name: "estado", label: "UF", type: "text", column: true },
      { name: "ddd_telefone", label: "DDD telefone", type: "number" },
      { name: "telefone", label: "Telefone", type: "number" },
      { name: "ddd_celular", label: "DDD celular", type: "text" },
      { name: "celular", label: "Celular", type: "number" },
      { name: "email", label: "E-mail", type: "text", column: true },
      { name: "email_nfe", label: "E-mail NF-e", type: "text" },
      { name: "inscricao_estadual", label: "Inscrição estadual", type: "text" },
      {
        name: "situacao_cliente",
        label: "Situação",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Ativo" },
          { value: "2", label: "2 · Inativo" },
        ],
        column: true,
      },
      { name: "tipo_frete", label: "Tipo frete", type: "number", placeholder: "0-5" },
      { name: "forma_pagamento", label: "Forma de pagamento (código)", type: "text" },
      { name: "codigo_banco", label: "Código do banco", type: "number" },
      { name: "agencia_banco", label: "Agência", type: "number" },
      { name: "nome_contato", label: "Nome do contato", type: "text" },
      { name: "seq_endereco", label: "Seq. endereço", type: "number" },
      { name: "data_fundacao", label: "Data de fundação", type: "date" },
    ],
  },
  "systextil:fornecedor": {
    provider: "systextil",
    entity: "fornecedor",
    title: "Fornecedores (Systêxtil)",
    description:
      "Fornecedores cadastrados no ERP Systêxtil, com dados de contato, bancários, impostos e materiais fornecidos.",
    idField: "cnpj_9_fornecedor",
    keyFields: ["cnpj_9_fornecedor", "cnpj_4_fornecedor", "cnpj_2_fornecedor"],
    basePath: "/pessoa/v1/fornecedor",
    fields: [
      { name: "cnpj_9_fornecedor", label: "CNPJ/CPF (9 dígitos)", type: "number", required: true, column: true },
      { name: "cnpj_4_fornecedor", label: "CNPJ (4 dígitos)", type: "number", required: true, column: true },
      { name: "cnpj_2_fornecedor", label: "CNPJ (2 dígitos)", type: "number", required: true, column: true },
      { name: "nome_fornecedor", label: "Nome / Razão social", type: "text", column: true },
      { name: "nome_fantasia", label: "Nome fantasia", type: "text" },
      { name: "tipo_fornecedor_id", label: "Código do tipo", type: "number", required: true, placeholder: "código do tipo" },
      { name: "codigo_fornecedor", label: "Código do fornecedor", type: "text" },
      { name: "cep_fornecedor", label: "CEP", type: "number", required: true },
      { name: "endereco_fornecedor", label: "Endereço", type: "text", required: true, column: true },
      { name: "numero_fornecedor", label: "Número", type: "text", required: true },
      { name: "complemento_fornecedor", label: "Complemento", type: "text" },
      { name: "bairro_fornecedor", label: "Bairro", type: "text", required: true },
      { name: "cidade_fornecedor_id", label: "Código da cidade", type: "number", required: true },
      { name: "cidade_fornecedor_descricao", label: "Cidade", type: "text", column: true },
      { name: "codigo_ibge_fornecedor", label: "Código IBGE", type: "number" },
      { name: "estado_fornecedor", label: "UF", type: "text", column: true },
      { name: "telefone_fornecedor", label: "Telefone", type: "number", column: true },
      { name: "ddd_celular_fornecedor", label: "DDD celular", type: "number" },
      { name: "celular_fornecedor", label: "Celular", type: "number" },
      { name: "site_fornecedor", label: "Site", type: "text" },
      { name: "email_fornecedor", label: "E-mail", type: "text", column: true },
      { name: "email_nfe_fornecedor", label: "E-mail NF-e", type: "text" },
      { name: "inscricao_estadual_fornecedor", label: "Inscrição estadual", type: "text" },
      { name: "inscricao_municipal_fornecedor", label: "Inscrição municipal", type: "text" },
      { name: "observacoes_fornecedor", label: "Observações", type: "text" },
      {
        name: "situacao_fornecedor",
        label: "Situação",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Ativo" },
          { value: "2", label: "2 · Inativo" },
          { value: "3", label: "3 · Não qualificado" },
          { value: "9", label: "9 · Pré-cadastro" },
        ],
        column: true,
      },
      { name: "condicao_pagamento_fornecedor_id", label: "Condição de pagamento (código)", type: "number" },
      { name: "nome_contato_fornecedor", label: "Nome do contato", type: "text", required: true },
      { name: "banco_fornecedor_id", label: "Código do banco", type: "number", required: true },
      { name: "agencia_fornecedor", label: "Agência", type: "number" },
      { name: "conta_fornecedor", label: "Conta", type: "number" },
      {
        name: "tipo_conta",
        label: "Tipo de conta",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Normal" },
          { value: "2", label: "2 · Poupança" },
        ],
      },
      { name: "moeda_id", label: "Código da moeda", type: "number", placeholder: "código da moeda" },
      {
        name: "tipo_chave_pix",
        label: "Tipo de chave PIX",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · CPF ou CNPJ" },
          { value: "2", label: "2 · E-mail" },
          { value: "3", label: "3 · Celular" },
          { value: "4", label: "4 · Chave aleatória" },
        ],
      },
      { name: "chave_pix", label: "Chave PIX", type: "text" },
      {
        name: "tipo_socio",
        label: "Sócio?",
        type: "select",
        options: [
          { value: "false", label: "Não sócio" },
          { value: "true", label: "Sócio" },
        ],
      },
    ],
  },
  "systextil:produto": {
    provider: "systextil",
    entity: "produto",
    title: "Produtos (Systêxtil)",
    description:
      "Produtos e materiais cadastrados no ERP Systêxtil, organizados por nível, grupo, subgrupo e item de estrutura.",
    idField: "item_estrutura_id",
    keyFields: ["nivel_produto", "grupo_id", "subgrupo_id", "item_estrutura_id"],
    searchField: "descricao_produto",
    basePath: "/material/v1/produto",
    fields: [
      {
        name: "nivel_produto",
        label: "Nível",
        type: "select",
        required: true,
        options: [
          { value: "1", label: "1 · Peça" },
          { value: "2", label: "2 · Tecido" },
          { value: "4", label: "4 · Tecido Cru" },
          { value: "5", label: "5 · Serviços" },
          { value: "7", label: "7 · Fio" },
          { value: "8", label: "8 · Largura Tecido" },
          { value: "9", label: "9 · Material Comprado" },
        ],
        column: true,
      },
      { name: "grupo_id", label: "Grupo", type: "text", required: true, column: true },
      { name: "subgrupo_id", label: "Subgrupo", type: "text", required: true, column: true },
      { name: "item_estrutura_id", label: "Item de estrutura", type: "text", required: true, column: true },
      { name: "item_estrutura_descricao", label: "Item (descrição)", type: "text" },
      { name: "descricao_produto", label: "Descrição", type: "text", column: true },
      { name: "descricao_produto_complementar", label: "Descrição complementar", type: "text" },
      {
        name: "situacao_produto",
        label: "Situação",
        type: "select",
        asNumber: true,
        options: [
          { value: "0", label: "0 · Ativo" },
          { value: "1", label: "1 · Inativo" },
          { value: "2", label: "2 · Lançamento" },
        ],
        column: true,
      },
      { name: "classificacao_fiscal", label: "Classificação fiscal", type: "text" },
      { name: "cest", label: "CEST", type: "text" },
      { name: "codigo_barras", label: "Código de barras", type: "text" },
      { name: "unidade_medida_id", label: "Unidade de medida (código)", type: "text" },
      { name: "unidade_medida_descricao", label: "Unidade de medida", type: "text", column: true },
      { name: "linha_produto_id", label: "Linha (código)", type: "number" },
      { name: "linha_produto_descricao", label: "Linha", type: "text", column: true },
      { name: "colecao_id", label: "Coleção (código)", type: "number" },
      { name: "colecao_descricao", label: "Coleção", type: "text", column: true },
      { name: "artigo_id", label: "Artigo (código)", type: "number" },
      { name: "artigo_descricao", label: "Artigo", type: "text" },
      { name: "grade_tamanho_id", label: "Grade (código)", type: "number" },
      { name: "conta_estoque_id", label: "Conta de estoque (código)", type: "number" },
      {
        name: "comprado_fabricado",
        label: "Comprado / Fabricado",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Comprado" },
          { value: "2", label: "2 · Fabricado" },
        ],
      },
      { name: "tipo_produto", label: "Tipo de produto", type: "number", placeholder: "conforme nível" },
      {
        name: "origem_produto",
        label: "Origem",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Nacional" },
          { value: "2", label: "2 · Importado" },
          { value: "3", label: "3 · Sem classificação" },
        ],
      },
      {
        name: "tipo_codigo_ean",
        label: "Grade de EAN",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Por cor" },
          { value: "2", label: "2 · Por tamanho" },
        ],
      },
      { name: "cor_de_estoque", label: "Cor/sortimento estoque", type: "text" },
      { name: "largura", label: "Largura", type: "number" },
      { name: "metragem", label: "Metragem do rolo", type: "number" },
      { name: "peso_oz", label: "Peso (oz)", type: "number" },
      { name: "codigo_acompanhamento", label: "Código de acompanhamento", type: "number" },
      { name: "observacao_produto", label: "Observações", type: "text" },
      {
        name: "produto_prototipo",
        label: "Produto protótipo?",
        type: "select",
        options: [
          { value: "true", label: "true" },
          { value: "false", label: "false" },
        ],
      },
    ],
  },
  "systextil:colecao": {
    provider: "systextil",
    entity: "colecao",
    title: "Coleções (Systêxtil)",
    description:
      "Coleções de produtos cadastradas no ERP Systêxtil. Endpoint /material/v1/colecao retornou 404 no tenant PRD (2026-09-05) - recurso pode estar desabilitado na assinatura. Verifique com a Systêxtil antes de usar.",
    idField: "colecao_id",
    keyFields: ["colecao_id"],
    searchField: "colecao_descricao",
    basePath: "/material/v1/colecao",
    fields: [
      { name: "colecao_id", label: "Código da coleção", type: "number", required: true, column: true },
      { name: "colecao_descricao", label: "Descrição", type: "text", required: true, column: true },
      { name: "colecao_descricao_ingles", label: "Descrição (inglês)", type: "text" },
      { name: "colecao_descricao_espanhol", label: "Descrição (espanhol)", type: "text" },
      {
        name: "disponivel_internet",
        label: "Disponível na internet?",
        type: "select",
        options: [
          { value: "true", label: "true" },
          { value: "false", label: "false" },
        ],
      },
    ],
  },
  "systextil:pedido-venda": {
    provider: "systextil",
    entity: "pedido-venda",
    title: "Pedidos de Venda (Systêxtil)",
    description:
      "Pedidos de venda do ERP Systêxtil, com cliente, itens, condições comerciais, transporte e faturamento.",
    idField: "codigo_pedido",
    keyFields: ["codigo_empresa_pedido", "codigo_pedido"],
    searchField: "nome_cliente",
    basePath: "/venda/v1/pedido/venda",
    fields: [
      { name: "codigo_empresa_pedido", label: "Empresa", type: "number", required: true, column: true },
      { name: "codigo_pedido", label: "Código do pedido", type: "number", required: true, column: true },
      { name: "codigo_pedido_cliente", label: "Pedido do cliente", type: "text", column: true },
      { name: "cnpj9_cliente", label: "CNPJ/CPF do cliente (9)", type: "number", column: true },
      { name: "cnpj4_cliente", label: "CNPJ do cliente (4)", type: "number" },
      { name: "cnpj2_cliente", label: "CNPJ do cliente (2)", type: "number" },
      { name: "nome_cliente", label: "Cliente", type: "text", column: true },
      { name: "estado_cliente", label: "UF do cliente", type: "text" },
      {
        name: "tipo_peca_pedido",
        label: "Tipo de peça",
        type: "select",
        options: [
          { value: "1", label: "1 · Peças" },
          { value: "2", label: "2 · Tecidos" },
          { value: "4", label: "4 · Tecidos crus" },
          { value: "7", label: "7 · Fios" },
        ],
      },
      {
        name: "tipo_pedido",
        label: "Tipo do pedido",
        type: "select",
        asNumber: true,
        options: [
          { value: "0", label: "0 · Programado" },
          { value: "1", label: "1 · Pronta entrega" },
        ],
      },
      {
        name: "tipo_produto_pedido",
        label: "Qualidade do produto",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Primeira qualidade" },
          { value: "2", label: "2 · Segunda qualidade" },
          { value: "3", label: "3 · Retalho" },
          { value: "4", label: "4 · Amostragem" },
          { value: "5", label: "5 · Exportação" },
          { value: "6", label: "6 · Desenvolvimento" },
        ],
      },
      {
        name: "tipo_promocao_pedido",
        label: "Promoção",
        type: "select",
        asNumber: true,
        options: [
          { value: "0", label: "0 · Não é promoção" },
          { value: "1", label: "1 · É promoção" },
          { value: "2", label: "2 · É desconto" },
        ],
      },
      { name: "origem_pedido", label: "Origem do pedido", type: "number" },
      { name: "data_emissao", label: "Data de emissão", type: "date", column: true },
      { name: "data_base_faturamento", label: "Data base faturamento", type: "date" },
      { name: "codigo_funcionario", label: "Funcionário (código)", type: "number" },
      { name: "codigo_representante", label: "Representante (código)", type: "number" },
      { name: "condicao_pagamento", label: "Condição de pagamento (código)", type: "number", column: true },
      { name: "percentual_desconto1", label: "Desconto 1 (%)", type: "number" },
      { name: "percentual_desconto2", label: "Desconto 2 (%)", type: "number" },
      { name: "percentual_desconto3", label: "Desconto 3 (%)", type: "number" },
      { name: "percentual_encargos", label: "Encargos (%)", type: "number" },
      { name: "moeda_id", label: "Moeda (código)", type: "number" },
      {
        name: "tipo_frete",
        label: "Tipo de frete",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Frete pago" },
          { value: "2", label: "2 · Frete a pagar" },
          { value: "3", label: "3 · Por conta de terceiros" },
          { value: "4", label: "4 · Cortesia" },
          { value: "5", label: "5 · Valor fechado" },
          { value: "6", label: "6 · Transporte próprio remetente" },
          { value: "7", label: "7 · Transporte próprio destinatário" },
        ],
      },
      {
        name: "via_transporte",
        label: "Via",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Terrestre" },
          { value: "2", label: "2 · Aéreo" },
          { value: "3", label: "3 · Marítimo" },
          { value: "4", label: "4 · Ferroviário" },
          { value: "5", label: "5 · Fluvial" },
        ],
      },
      { name: "forma_pagamento_id", label: "Forma de pagamento (código)", type: "number" },
      { name: "natureza_operacao", label: "Natureza da operação (código)", type: "number" },
      { name: "cfop_principal", label: "CFOP principal", type: "text" },
      { name: "codigo_banco", label: "Código do portador", type: "number" },
      {
        name: "status_pedido",
        label: "Status",
        type: "select",
        asNumber: true,
        options: [
          { value: "0", label: "0 · Digitado" },
          { value: "1", label: "1 · Financeiro" },
          { value: "2", label: "2 · Liberado financeiro" },
          { value: "3", label: "3 · Faturamento" },
          { value: "4", label: "4 · A cancelar" },
          { value: "5", label: "5 · Cancelado" },
          { value: "9", label: "9 · Aberto na web" },
        ],
        column: true,
      },
      { name: "situacao_venda", label: "Situação da venda", type: "number", placeholder: "0/5/9/10/15/50/51/52/54/56/62/64/66/70/87" },
      { name: "quantidade_total_pedido", label: "Quantidade total", type: "number", column: true },
      { name: "valor_total_bruto_pedido", label: "Valor total bruto", type: "number", column: true },
      { name: "valor_total_liquido_pedido", label: "Valor total líquido", type: "number", column: true },
      { name: "quantidade_saldo_pedido", label: "Qtde. de saldo", type: "number" },
      { name: "valor_saldo_pedido", label: "Valor de saldo", type: "number" },
      { name: "pedido_mae", label: "Pedido mãe?", type: "select", options: [{ value: "S", label: "S" }, { value: "N", label: "N" }] },
    ],
  },
};

export function getCrudEntity(
  provider: string,
  entity: string
): CrudEntitySchema | null {
  return CRUD_ENTITIES[`${provider}:${entity}`] ?? null;
}