// Registro schema-driven de entidades CRUD.
// Dados puros (serializáveis): podem ser importados pelo servidor e pelo cliente.
import type { CrudEntitySchema } from "./types";

export const CRUD_ENTITIES: Record<string, CrudEntitySchema> = {
  "bling:contatos": {
    provider: "bling",
    entity: "contatos",
    title: "Contatos no Bling",
    description:
      "Clientes, fornecedores e transportadoras cadastrados no Bling V3.",
    idField: "id",
    basePath: "/contatos",
    fields: [
      {
        name: "tipo",
        label: "Tipo de pessoa",
        type: "select",
        required: true,
        options: [
          { value: "F", label: "F · Física" },
          { value: "J", label: "J · Jurídica" },
          { value: "E", label: "E · Estrangeira" },
        ],
        column: true,
      },
      { name: "nome", label: "Nome", type: "text", required: true, column: true },
      { name: "numeroDocumento", label: "CPF / CNPJ", type: "text", column: true },
      {
        name: "situacao",
        label: "Situação",
        type: "select",
        options: [
          { value: "A", label: "A · Ativo" },
          { value: "I", label: "I · Inativo" },
          { value: "E", label: "E · Excluído" },
          { value: "S", label: "S · Sem movimento" },
        ],
        column: true,
      },
      { name: "codigo", label: "Código", type: "text" },
      { name: "fantasia", label: "Nome fantasia", type: "text" },
      { name: "telefone", label: "Telefone", type: "text" },
      { name: "celular", label: "Celular", type: "text" },
      { name: "email", label: "E-mail", type: "text" },
    ],
  },
  "systextil:cliente": {
    provider: "systextil",
    entity: "cliente",
    title: "Clientes (Systêxtil)",
    description:
      "Clientes cadastrados no ERP Systêxtil, com endereço, contato e condições comerciais.",
    idField: "cnpj_9",
    keyFields: ["cnpj_9", "cnpj_4", "cnpj_2"],
    basePath: "/pessoa/v1/cliente",
    fields: [
      { name: "cnpj_9", label: "CNPJ/CPF (9 dígitos)", type: "number", required: true, column: true },
      { name: "cnpj_4", label: "CNPJ (4 dígitos)", type: "number", required: true, column: true },
      { name: "cnpj_2", label: "CNPJ (2 dígitos)", type: "number", required: true, column: true },
      { name: "nome_cliente", label: "Nome / Razão social", type: "text", required: true, column: true },
      { name: "fantasia_cliente", label: "Nome fantasia", type: "text" },
      {
        name: "fisica_juridica",
        label: "Física / Jurídica",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Pessoa Física" },
          { value: "2", label: "2 · Pessoa Jurídica" },
        ],
        column: true,
      },
      { name: "cep", label: "CEP", type: "number" },
      { name: "logradouro", label: "Logradouro", type: "text" },
      { name: "numero", label: "Número", type: "text" },
      { name: "complemento", label: "Complemento", type: "text" },
      { name: "bairro", label: "Bairro", type: "text" },
      { name: "cidade_descricao", label: "Cidade", type: "text", column: true },
      { name: "estado", label: "UF", type: "text", column: true },
      { name: "ddd_telefone", label: "DDD telefone", type: "number" },
      { name: "telefone", label: "Telefone", type: "number" },
      { name: "ddd_celular", label: "DDD celular", type: "text" },
      { name: "celular", label: "Celular", type: "number" },
      { name: "email", label: "E-mail", type: "text", column: true },
      { name: "email_nfe", label: "E-mail NF-e", type: "text" },
      { name: "inscricao_estadual", label: "Inscrição estadual", type: "text" },
      {
        name: "situacao_cliente",
        label: "Situação",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Ativo" },
          { value: "2", label: "2 · Inativo" },
        ],
        column: true,
      },
      { name: "tipo_frete", label: "Tipo frete", type: "number", placeholder: "0-5" },
      { name: "forma_pagamento", label: "Forma de pagamento (código)", type: "text" },
      { name: "codigo_banco", label: "Código do banco", type: "number" },
      { name: "agencia_banco", label: "Agência", type: "number" },
      { name: "nome_contato", label: "Nome do contato", type: "text" },
      { name: "seq_endereco", label: "Seq. endereço", type: "number" },
      { name: "data_fundacao", label: "Data de fundação", type: "date" },
    ],
  },
  "systextil:fornecedor": {
    provider: "systextil",
    entity: "fornecedor",
    title: "Fornecedores (Systêxtil)",
    description:
      "Fornecedores cadastrados no ERP Systêxtil, com dados de contato, bancários, impostos e materiais fornecidos.",
    idField: "cnpj_9_fornecedor",
    keyFields: ["cnpj_9_fornecedor", "cnpj_4_fornecedor", "cnpj_2_fornecedor"],
    basePath: "/pessoa/v1/fornecedor",
    fields: [
      { name: "cnpj_9_fornecedor", label: "CNPJ/CPF (9 dígitos)", type: "number", required: true, column: true },
      { name: "cnpj_4_fornecedor", label: "CNPJ (4 dígitos)", type: "number", required: true, column: true },
      { name: "cnpj_2_fornecedor", label: "CNPJ (2 dígitos)", type: "number", required: true, column: true },
      { name: "nome_fornecedor", label: "Nome / Razão social", type: "text", column: true },
      { name: "nome_fantasia", label: "Nome fantasia", type: "text" },
      { name: "tipo_fornecedor_id", label: "Código do tipo", type: "number", required: true, placeholder: "código do tipo" },
      { name: "codigo_fornecedor", label: "Código do fornecedor", type: "text" },
      { name: "cep_fornecedor", label: "CEP", type: "number", required: true },
      { name: "endereco_fornecedor", label: "Endereço", type: "text", required: true, column: true },
      { name: "numero_fornecedor", label: "Número", type: "text", required: true },
      { name: "complemento_fornecedor", label: "Complemento", type: "text" },
      { name: "bairro_fornecedor", label: "Bairro", type: "text", required: true },
      { name: "cidade_fornecedor_id", label: "Código da cidade", type: "number", required: true },
      { name: "cidade_fornecedor_descricao", label: "Cidade", type: "text", column: true },
      { name: "codigo_ibge_fornecedor", label: "Código IBGE", type: "number" },
      { name: "estado_fornecedor", label: "UF", type: "text", column: true },
      { name: "telefone_fornecedor", label: "Telefone", type: "number", column: true },
      { name: "ddd_celular_fornecedor", label: "DDD celular", type: "number" },
      { name: "celular_fornecedor", label: "Celular", type: "number" },
      { name: "site_fornecedor", label: "Site", type: "text" },
      { name: "email_fornecedor", label: "E-mail", type: "text", column: true },
      { name: "email_nfe_fornecedor", label: "E-mail NF-e", type: "text" },
      { name: "inscricao_estadual_fornecedor", label: "Inscrição estadual", type: "text" },
      { name: "inscricao_municipal_fornecedor", label: "Inscrição municipal", type: "text" },
      { name: "observacoes_fornecedor", label: "Observações", type: "text" },
      {
        name: "situacao_fornecedor",
        label: "Situação",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Ativo" },
          { value: "2", label: "2 · Inativo" },
          { value: "3", label: "3 · Não qualificado" },
          { value: "9", label: "9 · Pré-cadastro" },
        ],
        column: true,
      },
      { name: "condicao_pagamento_fornecedor_id", label: "Condição de pagamento (código)", type: "number" },
      { name: "nome_contato_fornecedor", label: "Nome do contato", type: "text", required: true },
      { name: "banco_fornecedor_id", label: "Código do banco", type: "number", required: true },
      { name: "agencia_fornecedor", label: "Agência", type: "number" },
      { name: "conta_fornecedor", label: "Conta", type: "number" },
      {
        name: "tipo_conta",
        label: "Tipo de conta",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Normal" },
          { value: "2", label: "2 · Poupança" },
        ],
      },
      { name: "moeda_id", label: "Código da moeda", type: "number", placeholder: "código da moeda" },
      {
        name: "tipo_chave_pix",
        label: "Tipo de chave PIX",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · CPF ou CNPJ" },
          { value: "2", label: "2 · E-mail" },
          { value: "3", label: "3 · Celular" },
          { value: "4", label: "4 · Chave aleatória" },
        ],
      },
      { name: "chave_pix", label: "Chave PIX", type: "text" },
      {
        name: "tipo_socio",
        label: "Sócio?",
        type: "select",
        options: [
          { value: "false", label: "Não sócio" },
          { value: "true", label: "Sócio" },
        ],
      },
    ],
  },
  "systextil:produto": {
    provider: "systextil",
    entity: "produto",
    title: "Produtos (Systêxtil)",
    description:
      "Produtos e materiais cadastrados no ERP Systêxtil, organizados por nível, grupo, subgrupo e item de estrutura.",
    idField: "item_estrutura_id",
    keyFields: ["nivel_produto", "grupo_id", "subgrupo_id", "item_estrutura_id"],
    searchField: "descricao_produto",
    basePath: "/material/v1/produto",
    fields: [
      {
        name: "nivel_produto",
        label: "Nível",
        type: "select",
        required: true,
        options: [
          { value: "1", label: "1 · Peça" },
          { value: "2", label: "2 · Tecido" },
          { value: "4", label: "4 · Tecido Cru" },
          { value: "5", label: "5 · Serviços" },
          { value: "7", label: "7 · Fio" },
          { value: "8", label: "8 · Largura Tecido" },
          { value: "9", label: "9 · Material Comprado" },
        ],
        column: true,
      },
      { name: "grupo_id", label: "Grupo", type: "text", required: true, column: true },
      { name: "subgrupo_id", label: "Subgrupo", type: "text", required: true, column: true },
      { name: "item_estrutura_id", label: "Item de estrutura", type: "text", required: true, column: true },
      { name: "item_estrutura_descricao", label: "Item (descrição)", type: "text" },
      { name: "descricao_produto", label: "Descrição", type: "text", column: true },
      { name: "descricao_produto_complementar", label: "Descrição complementar", type: "text" },
      {
        name: "situacao_produto",
        label: "Situação",
        type: "select",
        asNumber: true,
        options: [
          { value: "0", label: "0 · Ativo" },
          { value: "1", label: "1 · Inativo" },
          { value: "2", label: "2 · Lançamento" },
        ],
        column: true,
      },
      { name: "classificacao_fiscal", label: "Classificação fiscal", type: "text" },
      { name: "cest", label: "CEST", type: "text" },
      { name: "codigo_barras", label: "Código de barras", type: "text" },
      { name: "unidade_medida_id", label: "Unidade de medida (código)", type: "text" },
      { name: "unidade_medida_descricao", label: "Unidade de medida", type: "text", column: true },
      { name: "linha_produto_id", label: "Linha (código)", type: "number" },
      { name: "linha_produto_descricao", label: "Linha", type: "text", column: true },
      { name: "colecao_id", label: "Coleção (código)", type: "number" },
      { name: "colecao_descricao", label: "Coleção", type: "text", column: true },
      { name: "artigo_id", label: "Artigo (código)", type: "number" },
      { name: "artigo_descricao", label: "Artigo", type: "text" },
      { name: "grade_tamanho_id", label: "Grade (código)", type: "number" },
      { name: "conta_estoque_id", label: "Conta de estoque (código)", type: "number" },
      {
        name: "comprado_fabricado",
        label: "Comprado / Fabricado",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Comprado" },
          { value: "2", label: "2 · Fabricado" },
        ],
      },
      { name: "tipo_produto", label: "Tipo de produto", type: "number", placeholder: "conforme nível" },
      {
        name: "origem_produto",
        label: "Origem",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Nacional" },
          { value: "2", label: "2 · Importado" },
          { value: "3", label: "3 · Sem classificação" },
        ],
      },
      {
        name: "tipo_codigo_ean",
        label: "Grade de EAN",
        type: "select",
        asNumber: true,
        options: [
          { value: "1", label: "1 · Por cor" },
          { value: "2", label: "2 · Por tamanho" },
        ],
      },
      { name: "cor_de_estoque", label: "Cor/sortimento estoque", type: "text" },
      { name: "largura", label: "Largura", type: "number" },
      { name: "metragem", label: "Metragem do rolo", type: "number" },
      { name: "peso_oz", label: "Peso (oz)", type: "number" },
      { name: "codigo_acompanhamento", label: "Código de acompanhamento", type: "number" },
      { name: "observacao_produto", label: "Observações", type: "text" },
      {
        name: "produto_prototipo",
        label: "Produto protótipo?",
        type: "select",
        options: [
          { value: "true", label: "true" },
          { value: "false", label: "false" },
        ],
      },
    ],
  },
};

export function getCrudEntity(
  provider: string,
  entity: string
): CrudEntitySchema | null {
  return CRUD_ENTITIES[`${provider}:${entity}`] ?? null;
}